config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # 管理者
  namespace :admin do
    resources :contacts, only: [:create, :index, :show]
    resources :reviews, only: [:edit, :update, :destroy]
    resources :labels, only: [:create, :edit, :update, :new, :destroy]
    resources :categories, only: [:create, :edit, :update, :new, :destroy]
    resources :artists, only: [:create, :edit, :update, :new, :destroy]
    resources :orders, only: [:show, :index, :update]
    resources :arrivals, only: [:new, :create, :index, :edit]
    resources :items, only: [:show, :edit, :new, :create, :update, :index, :destroy]
    get 'items/autocomplete_artist/:term' => 'items#autocomplete_artist'
    get 'items/autocomplete_category/:term' => 'items#autocomplete_category'
    get 'items/autocomplete_label/:term' => 'items#autocomplete_label'
    resources :users, only: [:show, :edit, :update, :index, :destroy]
  end
  # ユーザー
  devise_for :users
  get 'users/:id/exit' => 'users#exit', as: 'exit'
  get 'users/:id/mypage' => 'users#mypage', as: 'mypage'
  resources :items, only: [:index, :show]

  root to: 'items#index'
  resources :cart_items, only: [:create, :destroy, :index, :update]
  resources :orders, only: [:create, :index, :new]
  get 'orders/complete' => 'orders#complete', as:'order_complete'
  get 'reviews/new/:id' => 'reviews#new', as:'new_review'
  post 'orders/pay' => 'orders#pay', as:'order_pay'
  resources :addresses, only: [:create, :update, :destroy]
  resources :credits, only: [:create]
  get 'reviews/:id/new' => 'reviews#new', as: 'reviews_new'
  post 'reviews/:id' => 'reviews#create', as: 'reviews_create'
  resources :contacts, only: [:create, :new]
  resources :users, only: [:edit, :update, :show]
  resources :favorites, only: [:index]
  delete 'favorites/destroy_all' => 'favorites#destroy_all', as: 'destroy_all'
  resources :items, only: [:index, :show] do
  resources :favorites, only: [:create, :destroy]
end
  get 'items/index/result' => 'items#index_result', as: 'index_result'
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment: { "クレジット": 0, "銀行振込": 1, "代引": 2 }
  enum delivery_status: { "未受付": 0, "受付済": 1, "出荷準備中": 2, "出荷済": 3, "配送済": 4 }

  has_many :item_orders

  has_many :items, through: :item_orders
  belongs_to :user
  belongs_to :address,optional: true
  accepts_nested_attributes_for :item_orders, allow_destroy: true
acts_as_paranoid
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    if admin_signed_in?
  	@q = Order.ransack(params[:q])
    @order_results = @q.result(distinct: true).page(params[:page]).per(30)

   	@total_quantity = 0

   else
    redirect_to root_path
  end

  end

  def update
  	@order = Order.find(params[:id])
  	if @order.update(order_params)
  		redirect_to admin_orders_path
  	else
  		render 'index'
  	end
  end



  def show
    if admin_signed_in?
    @user = User.find(params[:id])
  	@orders = Order.where(user_id: @user.id).page(params[:page]).per(30)
  else
    redirect_to root_path
  end
  end

  private
  def order_params
  	params.require(:order).permit(:name, :user_id, :postal_code, :order_address, :payment, :total, :delivery_status, :delivery_fee)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.page(params[:page]).reverse_order
    @user = current_user
  end

  def new
  	@user = current_user
  	@order = Order.new
  	@order.build_user
    @delivery_fee = @order.delivery_fee
    @item_order = @order.item_orders.build
  	@addresses = @user.addresses
    @cart_items = CartItem.all
    @order_pay = Payjp::Charge.new
    @total_price = 0
    @cart_items.each do |cart_item|
      item = Item.where(id: cart_item.item_id)
      @total_price = @total_price + cart_item.item.include_tax_price * cart_item.quantity
    end
    @total_quantity = @cart_items.sum(:quantity)
  end

  def confirm
  end

  def create
    unless params['payjp-token'].blank?
      Payjp.api_key = 'sk_test_46e2a7941c4d2d62892e6ee9' # 秘密鍵 環境変数化しましょう
        charge = Payjp::Charge.create(
        :amount => params[:order][:total],
        :card => params['payjp-token'],
        :currency => 'jpy',
        )
    end
      @order = Order.new(order_params)
      @cart_items = CartItem.all
      if params['add_address'] == "other"
        @user = Address.create(
        user_id: current_user.id,
        name: params[:order][:address][:name],
        postal_code: params[:order][:address][:postal_code],
        address: params[:order][:address][:order_address]
        )
        @order.order_address = params[:order][:address][:order_address]
        @order.postal_code = params[:order][:address][:postal_code]
        @order.name = params[:order][:address][:name]
      elsif params['add_address'] == "me"
        @user = current_user
        @order.order_address = @user.residence
        @order.postal_code = @user.postal_code
        @order.name = @user.last_name
      else
        @address = Address.find(params[:add_address].to_i)
        @order.order_address = @address.address
        @order.postal_code = @address.postal_code
        @order.name = @address.name
      end
      if params['order']['payment'] == "クレジット"
        @order.payment = 0
      elsif params['order']['payment'] == "銀行振込"
        @order.payment = 1
      else
        @order.payment = 2
      end
      @order.user_id = current_user.id
      if @order.save
        @cart_items.each do |cart_item|
          @item_order = @order.item_orders.build
          @item_order.item_id = cart_item.item.id
          @item_order.quantity = cart_item.quantity
          @item_order.price = cart_item.item.include_tax_price
          @item_order.save
        end
        @cart_items.destroy_all
        redirect_to order_complete_path
      else
        @user = current_user
        render :new
      end
  end

  private
  def order_params
    params.require(:order).permit(:name,:delivery_fee,:total,:postal_code,:card_num, :card_name, :securitycode,:payment,:order_address, address_attributes:[:id,:name,:address, :postal_code,:deleted_at],item_order_attributes:[:id,:item_id,:quantity,:price])

  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<%= render 'admin/sidemenu' %>
	<div class="col-xs-9">
		<h3 class="edit-items">受注履歴一覧</h3>
		<div class="border"></div>

		<%= search_form_for @q, url: admin_orders_path do |f| %>
			<div class="deliver-status-search-radio">
					<%= f.radio_button :delivery_status_eq, 0 %>未受付
					<%= f.radio_button :delivery_status_eq, 1 %>受付済
					<%= f.radio_button :delivery_status_eq, 2 %>出荷準備中
					<%= f.radio_button :delivery_status_eq, 3 %>出荷済
					<%= f.radio_button :delivery_status_eq, 4 %>配達済

			<span class="actions"><%= f.submit "検索", class:"btn btn-success" %></span>

			</div>



			<% end %>


		<% @order_results.each do |order| %>

		<div class="admin-order-index">

			<div class="admin-order-id-box">
				<div class="row">
				<div class="col-xs-3">
				<span class="admin-order-id">受注ID: <%= order.id %></span>
				</div>
				<%= form_for (order), url: admin_order_path(order.id) do |f| %>
				<div class="col-xs-4 col-xs-offset-4">
				<% f.hidden_field :id, value:order.id %>
				<label class="delivery-status-change">配送状況変更: </label>
				<%= f.select :delivery_status, Order.delivery_statuses.keys %>
				<%= f.submit "変更" %>
				</div>
				</div>
				<% end %>
			</div>

				<div class="admin-order-box-head">
					<div class="row">
						<div class="col-xs-4">
						<span class="admin-order-date-text">受注日: <%= order.created_at.strftime("%Y年%m月%d日") %></span>
						</div>

						<div class="col-xs-4 col-xs-offset-1">
						<span class="admin-order-total-price">合計金額: <%= order.total %>円</span>
						</div>

						<div class="col-xs-2">
							<% if order.delivery_status == "未受付" %>
							<div class="admin-order-delivery-status-box-0">
								<span class="admin-order-delivery-status"><%= order.delivery_status %></span>
							</div>
							<% elsif order.delivery_status == "受付済" %>
							<div class="admin-order-delivery-status-box-1">
								<span class="admin-order-delivery-status"><%= order.delivery_status %></span>
							</div>
							<% elsif order.delivery_status == "出荷準備中" %>
							<div class="admin-order-delivery-status-box-2">
								<span class="admin-order-delivery-status"><%= order.delivery_status %></span>
							</div>
							<% elsif order.delivery_status == "出荷済" %>
							<div class="admin-order-delivery-status-box-3">
								<span class="admin-order-delivery-status"><%= order.delivery_status %></span>
							</div>
							<% else %>
							<div class="admin-order-delivery-status-box-4">
								<span class="admin-order-delivery-status"><%= order.delivery_status %></span>
						</div>
						<% end %>
						</div>

						</div>
					</div>

				<div class="admin-order-box">
					<div class="row">
						<div class="col-xs-4 col-xs-offset-1">
							<div class="admin-order-user-info">
								<div class="admin-order-user">
									<span class="admin-order-user-id">ID: <%= order.user_id %></span><br>
									<span class="admin-order-user-name">購入者: <%= order.user.last_name %><%= order.user.first_name %></span>
								</div>
								<div class="admin-order-address">
									<span class="admin-order-order-address">〒 <%= order.postal_code %><br>
										住所:<%= order.order_address %><br><br>
										送料:<%= order.delivery_fee %>円</span>
								</div>
							</div>
						</div>
						
						<% order.item_orders.each do |item_order| %>
						<div class="row">
						<div class="col-xs-4 col-xs-offset-1">
						</div>
						<div class="col-xs-2">
								<div class="admin-order-samuneiru-position">
								<%= attachment_image_tag item_order.item, :image, :fill, 160, 160, format: 'jpg', fallback: "no_image.jpg" %>
								</div>
							</div>

							<div class="col-xs-4">
								<div class="admin-order-item-info">
								<div class="admin-order-item-name">
									<span class="admin-order-item-name-text"><%= item_order.item.name %></span>
								</div>
								<div class="admin-order-artist-name">
									<span class="admin-order-artist-name-text"><%= item_order.item.artist.name %></span>
								</div>
								<div class="admin-order-item-quantity">
									<span class="admin-order-item-quantity-text">数量: <%= item_order.quantity %>点   単価: <%= item_order.item.price %>円</span>
								</div>
								<div class="admin-order-item-total">
									<span class="admin-order-item-total-text">小計: <%= item_order.item.price.to_i * item_order.quantity.to_i %>円</span>
								</div>
							</div>
							</div>
						</div>
						<% end %>


						</div>
						</div>
						</div>
						<% end %>
							<div class="back-to-item-index">
							 <%= link_to "< 商品一覧へ", admin_items_path %>
							</div>
	</div>

app/views/admin/orders/show.html.erb
<%= render 'admin/sidemenu' %>
	<div class="col-xs-9">
		<h3 class="edit-items">受注履歴一覧（<%= @user.last_name %>　様）</h3>
		<div class="border"></div>

		<% @orders.each do |order| %>

		<div class="admin-order-index">

			<div class="admin-order-id-box">
				<div class="row">
				<div class="col-xs-3">
				<span class="admin-order-id">受注ID: <%= order.id %></span>
				</div>
			</div>

				<div class="admin-order-box-head">
					<div class="row">
						<div class="col-xs-4">
						<span class="admin-order-date-text">受注日: <%= order.created_at.strftime("%Y年%m月%d日") %></span>
						</div>

						<div class="col-xs-4 col-xs-offset-1">
						<span class="admin-order-total-price">合計金額: <%= order.total %>(送料<%= order.delivery_fee %>円)</span>
						</div>

						<div class="col-xs-2">
						<div class="admin-order-delivery-status-box">
						<span class="admin-order-delivery-status"><%= order.delivery_status %></span>
						</div>
						</div>

						</div>
					</div>

				<div class="admin-order-box">
					<div class="row">
						<div class="col-xs-4 col-xs-offset-1">
							<div class="admin-order-user-info">
								<div class="admin-order-user">
									<span class="admin-order-user-id">ID: <%= order.user_id %></span><br>
									<span class="admin-order-user-name">購入者: <%= order.user.last_name %><%= order.user.first_name %></span>
								</div>
								<div class="admin-order-address">
									<span class="admin-order-order-address">〒 <%= order.postal_code %><br>
										住所:<%= order.order_address %></span>
								</div>
							</div>
						</div>
						<% order.item_orders.each do |item_order| %>
						<div class="row">
						<div class="col-xs-4 col-xs-offset-1">
						</div>
						<div class="col-xs-2">
								<div class="admin-order-samuneiru-position">
								<%= attachment_image_tag item_order.item, :image, :fill, 160, 160, format: 'jpg', fallback: "no_image.jpg" %>
								</div>
							</div>

							<div class="col-xs-4">
								<div class="admin-order-item-info">
								<div class="admin-order-item-name">
									<span class="admin-order-item-name-text"><%= item_order.item.name %></span>
								</div>
								<div class="admin-order-artist-name">
									<span class="admin-order-artist-name-text"><%= item_order.item.artist.name %></span>
								</div>
								<div class="admin-order-item-quantity">
									<span class="admin-order-item-quantity-text">数量: <%= item_order.quantity %>点   単価: <%= item_order.item.price %>円</span>
								</div>
								<div class="admin-order-item-total">
									<span class="admin-order-item-total-text">小計: <%= item_order.item.price.to_i * item_order.quantity.to_i %>円</span>
								</div>
							</div>
							</div>
						</div>
						<% end %>


						</div>
						</div>
						</div>
						<% end %>

						<%= link_to "顧客詳細へ", admin_user_path(@user.id) %>
	</div>