config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # 管理者
  namespace :admin do
    resources :contacts, only: [:create, :index, :show]
    resources :reviews, only: [:edit, :update, :destroy]
    resources :labels, only: [:create, :edit, :update, :new, :destroy]
    resources :categories, only: [:create, :edit, :update, :new, :destroy]
    resources :artists, only: [:create, :edit, :update, :new, :destroy]
    resources :orders, only: [:show, :index, :update]
    resources :arrivals, only: [:new, :create, :index, :edit]
    resources :items, only: [:show, :edit, :new, :create, :update, :index, :destroy]
    get 'items/autocomplete_artist/:term' => 'items#autocomplete_artist'
    get 'items/autocomplete_category/:term' => 'items#autocomplete_category'
    get 'items/autocomplete_label/:term' => 'items#autocomplete_label'
    resources :users, only: [:show, :edit, :update, :index, :destroy]
  end
  # ユーザー
  devise_for :users
  get 'users/:id/exit' => 'users#exit', as: 'exit'
  get 'users/:id/mypage' => 'users#mypage', as: 'mypage'
  resources :items, only: [:index, :show]

  root to: 'items#index'
  resources :cart_items, only: [:create, :destroy, :index, :update]
  resources :orders, only: [:create, :index, :new]
  get 'orders/complete' => 'orders#complete', as:'order_complete'
  get 'reviews/new/:id' => 'reviews#new', as:'new_review'
  post 'orders/pay' => 'orders#pay', as:'order_pay'
  resources :addresses, only: [:create, :update, :destroy]
  resources :credits, only: [:create]
  get 'reviews/:id/new' => 'reviews#new', as: 'reviews_new'
  post 'reviews/:id' => 'reviews#create', as: 'reviews_create'
  resources :contacts, only: [:create, :new]
  resources :users, only: [:edit, :update, :show]
  resources :favorites, only: [:index]
  delete 'favorites/destroy_all' => 'favorites#destroy_all', as: 'destroy_all'
  resources :items, only: [:index, :show] do
  resources :favorites, only: [:create, :destroy]
end
  get 'items/index/result' => 'items#index_result', as: 'index_result'
end

app/models/item.rb
class Item < ApplicationRecord
  acts_as_paranoid
  enum status: { "販売中": 0, "販売停止中": 1 }

  has_many :arrivals
  has_many :favorites
  has_many :favorited_users, through: :favorites, source: :user
  has_many :item_orders
  has_many :orders, through: :item_orders
  has_many :reviews
  has_many :cart_item
  belongs_to :artist
  belongs_to :category
  belongs_to :label

  def favorited_by?(user)
    self.favorites.where(user_id: user.id).exists?
  end

  attachment :image

  has_many :disks, inverse_of: :item
  #親要素のレコード時に、子要素のレコードも同時に行う。allow_destroyで子要素の削除を許可している。
  accepts_nested_attributes_for :disks, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true
  validates :price, presence: true
  validates :release, presence: true

  def include_tax_price
    (price * 1.1).round(0) 
  end

  def sales_status_change_to_1
    update_attributes(status: 1)
  end

  def sales_status_change_to_0
    update_attributes(status: 0)
  end

  def total_arrival_calculate
    total_arrival = 0
    self.arrivals.each do |arrival|
      total_arrival += arrival.arrival_quantity
    end
    return total_arrival
  end

    def total_item_order_calculate
    total_item_order = 0
    self.item_orders.each do |item_order|
      total_item_order += item_order.quantity
    end
    return total_item_order
  end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    if admin_signed_in?
    @search = Item.includes(:artist,:category,:label).ransack(params[:q])
    @item_result = @search.result.page(params[:page]).per(30)
  else
    redirect_to root_path
  end
  end

  def show
    if admin_signed_in?
    @item = Item.find(params[:id])
    @disks = Disk.where(item_id: @item.id)
    songs = Song.joins(:@disk).where(disk_id: {item_id: @item.id})

    @reviews = Review.where(item_id: @item.id).page(params[:page]).per(5)
    @reviews = Review.page(params[:page]).per(5)
    @review = Review.all

    @arrivals = Arrival.where(item_id: @item.id)
    @item_orders = ItemOrder.where(item_id: @item.id)
    @total_arrival = 0
    @total_order = 0
      @arrivals.each do |arrival|
        @total_arrival = @total_arrival + arrival.arrival_quantity
      end
      @item_orders.each do |item_order|
        @total_order = @total_order + item_order.quantity
      end
    if @total_arrival - @total_order >= 1
      @item.update_attributes(status: 0)
    else
      @item.update_attributes(status: 1)
    end

  else
    redirect_to root_path
  end
  end

  def edit
    if admin_signed_in?
    @item = Item.find(params[:id])
    @disk = @item.disks.build
    @song = @disk.songs.build
  else
    redirect_to root_path
  end
  end

  def new
    if admin_signed_in?
    @item = Item.new
    @disk = @item.disks.build
    @song = @disk.songs.build
  else
    redirect_to root_path
  end

  end

  def autocomplete_artist
    artist_suggestions = Artist.autocomplete(params[:term]).pluck(:name)
    respond_to do |format|
      format.html
      format.json{
        render json: artist_suggestions
      }
    end
  end

  def autocomplete_category
    category_suggestions = Category.autocomplete(params[:term]).pluck(:name)
    respond_to do |format|
      format.html
      format.json{
        render json: category_suggestions
      }
    end
  end

  def autocomplete_label
    label_suggestions = Label.autocomplete(params[:term]).pluck(:name)
    respond_to do |format|
      format.html
      format.json{
        render json: label_suggestions
      }
    end
  end

  def create
    @artist = Artist.find_by(name: params[:item][:artist_id])
    @label = Label.find_by(name: params[:item][:label_id])
    @category = Category.find_by(name: params[:item][:category_id])

    @item = Item.new(item_params)
    @item.artist_id = @artist.id
    @item.label_id = @label.id
    @item.category_id = @category.id1
    if @item.save
      redirect_to new_admin_item_path
    else
      render 'new'
  end
  end

  def update
    @artist = Artist.find_by(name: params[:item][:artist_id])
    @label = Label.find_by(name: params[:item][:label_id])
    @category = Category.find_by(name: params[:item][:category_id])

    @item = Item.find(params[:id])
    @item.artist_id = @artist.id
    @item.label_id = @label.id
    @item.category_id = @category.id
    if @item.update(item_params)
      redirect_to admin_item_path(params[:id])
    else
      render 'edit'
  end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
  end


  private
  #cocoon用記述。_destroyがないと削除できない。
  def item_params
    params.require(:item).permit(:name, :price, :release, :image, :sales_status, :artist_id, :label_id, :category_id,
      disks_attributes: [:id, :disk_num, :_destroy,
        songs_attributes: [:id, :name, :setlist, :_destroy]])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def show
    if user_signed_in?
    @item = Item.find(params[:id])
    @favorite = Favorite.new
    @user = current_user

    @disks = Disk.where(item_id: @item.id)
    songs = Song.joins(:@disk).where(disk_id: {item_id: @item.id})

    @cart_item = CartItem.new
    @user = User.find(current_user.id)
    @reviews = Review.where(item_id: @item.id)
    @reviews = Review.page(params[:page]).per(5)
    @review = Review.all

    @arrivals = Arrival.where(item_id: @item.id)
    @item_orders = ItemOrder.where(item_id: @item.id)
    @total_arrival = 0
    @total_order = 0
      @arrivals.each do |arrival|
        @total_arrival = @total_arrival + arrival.arrival_quantity
      end
      @item_orders.each do |item_order|
        @total_order = @total_order + item_order.quantity
      end
    if @total_arrival - @total_order >= 1
      @item.update_attributes(status: 0)
    else
      @item.update_attributes(status: 1)
    end

  else
    @item = Item.find(params[:id])

    @disks = Disk.where(item_id: @item.id)
    songs = Song.joins(:@disk).where(disk_id: {item_id: @item.id})
    @reviews = Review.where(item_id: @item.id)

    @arrivals = Arrival.where(item_id: @item.id)
    @item_orders = ItemOrder.where(item_id: @item.id)
    @total_arrival = 0
    @total_order = 0
      @arrivals.each do |arrival|
        @total_arrival = @total_arrival + arrival.arrival_quantity
      end
      @item_orders.each do |item_order|
        @total_order = @total_order + item_order.quantity
      end
    if @total_arrival - @total_order >= 1
      @item.update_attributes(status: 0)
    else
      @item.update_attributes(status: 1)
    end

  end
  end

  def index
  	@q = Item.ransack(params[:q])
    @q.build_condition if @q.conditions.empty?
    @items = @q.result(distinct: true).page(params[:page]).per(20)
    @all_ranks = Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(4).pluck(:item_id))

  	@search = Item.includes(:artist).ransack(params[:q])
    @items = @search.result.page(params[:page]).per(30)
  end

  def index_result
    @q = Item.ransack(params[:q])
    @q.build_condition if @q.conditions.empty?
    @items = @q.result(distinct: true).page(params[:page]).per(20)

    @search = Item.includes(:artist).ransack(params[:q])
    @items = @search.result.page(params[:page]).per(30)
  end

  private
  def cart_item_params
    params.require(:cart_item).permit(:quantity, :user_id, :item_id)
  end

  def favorite_params
    params.require(:favorite).permit(:user_id, :item_id)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<div class="search-box-user-index col-xs-8 col-xs-offset-3">


	<%= search_form_for @search, url: index_result_path do |f| %>
  		<%= f.search_field :artist_name_or_name_cont, class:"search_field", placeholder: '歌手・商品名を入力' %>

    	<span class="actions">
    		<%= f.button :type => "submit", class:'btn btn-primary' do %>
    		<i class="fas fa-search"></i>
    		<% end %>
    	</span>
    	<% end %>
</div>

<br><br><br>


	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">

        <div class="theTarget">
            <div class="pic1">
            	<div class="box-left"></div><div class="box-right"></div>
            </div>
            <div class="pic2">
            	<div class="box-left"></div><div class="box-right"></div>
            </div>
            <div class="pic3">
            	<div class="box-left"></div><div class="box-right"></div>
            </div>
            <div class="pic4">
            	<div class="box-left"></div><div class="box-right"></div>
            </div>
            <div class="pic5">
            	<div class="box-left"></div><div class="box-right"></div>
            </div>

        </div>
    </div>
</div>
        <br><br><br>



  <div class="container">
   <div class="row">
     <div class="col-xs-12">


     	<table>
     		<div class="ranking">
                <span class="ranking-text">いいね数ランキング</span></div>
     		<% @all_ranks.each_slice(4) do |item1, item2, item3, item4| %>
     		<tbody>
     			<tr class="item-index-tr">

     				<td class="item-index-td">
     					<% if item1 != nil%>
     					<%= link_to item_path(item1.id) do %>
     					<%= attachment_image_tag item1, :image, :fill, 230, 230, format: 'jpg', fallback: "no_image.jpg" %>
     					<% end %>
     						<div class="text-size">
     							<%=link_to item1.name, item_path(item1.id) %>
     						</div>
                            <div class="index-artist-box">
     							<%= item1.artist.name %>
                            </div>
     						 <div class="index-item-price-box">価格<span class="index-tax-text">(税込) </span>:　<%= item1.include_tax_price %>円</div>

                        <% if item1.total_arrival_calculate - item1.total_item_order_calculate >= 1 %>
                            <span class="index-user-stock-quantity">在庫数: 残り<%= item1.total_arrival_calculate - item1.total_item_order_calculate %>点</span>
                            <% else %>
                            <span class="index-stock-quantity">在庫無</span>
                            <span class="index-no-stock-text">【入荷待ち】</span>
                            <% end %>
     					<% end %>
     				</td>

     				<td class="item-index-td">
     					<% if item2 != nil%>
     					<%= link_to item_path(item2.id) do %>
     					<%= attachment_image_tag item2, :image, :fill, 230, 230, format: 'jpg', fallback: "no_image.jpg" %>
     					<% end %>
     						<div class="text-size">
     							<%=link_to item2.name, item_path(item2.id) %>
     						</div>
                             <div class="index-artist-box">
                                <%= item2.artist.name %>
                            </div>
                             <div class="index-item-price-box">価格<span class="index-tax-text">(税込) </span>:　<%= item2.include_tax_price %>円</div>

                        <% if item2.total_arrival_calculate - item2.total_item_order_calculate >= 1 %>
                            <span class="index-user-stock-quantity">在庫数: 残り<%= item2.total_arrival_calculate - item2.total_item_order_calculate %>点</span>
                            <% else %>
                            <span class="index-stock-quantity">在庫なし</span>
                            <span class="index-no-stock-text">【入荷待ち】</span>
                            <% end %>
     					<% end %>
     				</td>
     				<td class="item-index-td">
     					<% if item3 != nil%>
     					<%= link_to item_path(item3.id) do %>
     					<%= attachment_image_tag item3, :image, :fill, 230, 230, format: 'jpg', fallback: "no_image.jpg" %>
     					<% end %>
     						<div class="text-size">
     							<%=link_to item3.name, item_path(item3.id) %>
     						</div>
                             <div class="index-artist-box">
                                <%= item3.artist.name %>
                            </div>
                             <div class="index-item-price-box">価格<span class="index-tax-text">(税込) </span>:　<%= item3.include_tax_price %>円</div>

                        <% if item3.total_arrival_calculate - item3.total_item_order_calculate >= 1 %>
                            <span class="index-user-stock-quantity">在庫数: 残り<%= item3.total_arrival_calculate - item3.total_item_order_calculate %>点</span>
                            <% else %>
                            <span class="index-stock-quantity">在庫なし</span>
                            <span class="index-no-stock-text">【入荷待ち】</span>
                            <% end %>
     					<% end %>
     				</td>
     				<td class="item-index-td">
     					<% if item4 != nil%>
     					<%= link_to item_path(item4.id) do %>
     					<%= attachment_image_tag item4, :image, :fill, 230, 230, format: 'jpg', fallback: "no_image.jpg" %>
     					<% end %>
     						<div class="text-size">
     							<%=link_to item4.name, item_path(item4.id) %>
     						</div>
                             <div class="index-artist-box">
                                <%= item4.artist.name %>
                            </div>
                             <div class="index-item-price-box">価格<span class="index-tax-text">(税込) </span>:　<%= item4.include_tax_price %>円</div>

                        <% if item4.total_arrival_calculate - item4.total_item_order_calculate >= 1 %>
                            <span class="index-user-stock-quantity">在庫数: 残り<%= item4.total_arrival_calculate - item4.total_item_order_calculate %>点</span>
                            <% else %>
                            <span class="index-stock-quantity">在庫なし</span>
                            <span class="index-no-stock-text">【入荷待ち】</span>
                            <% end %>
     					<% end %>
     				</td>
     			</tr>
     		</tbody>
     		<% end %>
     	</table>


<table>
    <div class="index-index">
        <span class="index-index-text">商品一覧</span></div>

    <% @items.each_slice(4) do |item1, item2, item3, item4| %>

		<tbody>
				<tr class="item-index-tr">
						<td class="item-index-td">

						<% if item1 != nil%>
					       <%= link_to item_path(item1.id) do %>
					          <%= attachment_image_tag item1, :image, :fill, 230, 230, format: 'jpg', fallback: "no_image.jpg" %>
	                    <% end %>
						    <div class="text-size">
					           <%=link_to item1.name, item_path(item1.id) %>
					        </div>
                            <div class="index-artist-box">
                                <%= item1.artist.name %>
                            </div>
                             <div class="index-item-price-box">価格<span class="index-tax-text">(税込) </span>:　<%= item1.include_tax_price %>円</div>

                        <% if item1.total_arrival_calculate - item1.total_item_order_calculate >= 1 %>
                            <span class="index-user-stock-quantity">在庫数: 残り<%= item1.total_arrival_calculate - item1.total_item_order_calculate %>点</span>
                            <% else %>
                            <span class="index-stock-quantity">在庫無</span>
                            <span class="index-no-stock-text">【入荷待ち】</span>
                            <% end %>
                         <% end %>
	                   </td>

                       <td class="item-index-td">
                        <% if item2 != nil%>
                           <%= link_to item_path(item2.id) do %>
                              <%= attachment_image_tag item2, :image, :fill, 230, 230, format: 'jpg', fallback: "no_image.jpg" %>
                        <% end %>
                            <div class="text-size">
                               <%=link_to item2.name, item_path(item2.id) %>
                            </div>
                            <div class="index-artist-box">
                                <%= item2.artist.name %>
                            </div>
                             <div class="index-item-price-box">価格<span class="index-tax-text">(税込) </span>:　<%= item2.include_tax_price %>円</div>

                        <% if item2.total_arrival_calculate - item2.total_item_order_calculate >= 1 %>
                            <span class="index-user-stock-quantity">在庫数: 残り<%= item2.total_arrival_calculate - item2.total_item_order_calculate %>点</span>
                            <% else %>
                            <span class="index-stock-quantity">在庫無</span>
                            <span class="index-no-stock-text">【入荷待ち】</span>
                            <% end %>
                         <% end %>
                       </td>

                       <td class="item-index-td">
                        <% if item3 != nil%>
                           <%= link_to item_path(item3.id) do %>
                              <%= attachment_image_tag item3, :image, :fill, 230, 230, format: 'jpg', fallback: "no_image.jpg" %>
                        <% end %>
                            <div class="text-size">
                               <%=link_to item3.name, item_path(item3.id) %>
                            </div>
                            <div class="index-artist-box">
                                <%= item3.artist.name %>
                            </div>
                             <div class="index-item-price-box">価格<span class="index-tax-text">(税込) </span>:　<%= item3.include_tax_price %>円</div>

                        <% if item3.total_arrival_calculate - item3.total_item_order_calculate >= 1 %>
                            <span class="index-user-stock-quantity">在庫数: 残り<%= item3.total_arrival_calculate - item3.total_item_order_calculate %>点</span>
                            <% else %>
                            <span class="index-stock-quantity">在庫無</span>
                            <span class="index-no-stock-text">【入荷待ち】</span>
                            <% end %>
                         <% end %>
                       </td>

                       <td class="item-index-td">
                        <% if item4 != nil%>
                           <%= link_to item_path(item4.id) do %>
                              <%= attachment_image_tag item4, :image, :fill, 230, 230, format: 'jpg', fallback: "no_image.jpg" %>
                        <% end %>
                            <div class="text-size">
                               <%=link_to item4.name, item_path(item4.id) %>
                            </div>
                            <div class="index-artist-box">
                                <%= item4.artist.name %>
                            </div>
                             <div class="index-item-price-box">価格<span class="index-tax-text">(税込) </span>:　<%= item4.include_tax_price %>円</div>

                        <% if item4.total_arrival_calculate - item4.total_item_order_calculate >= 1 %>
                            <span class="index-user-stock-quantity">在庫数: 残り<%= item4.total_arrival_calculate - item4.total_item_order_calculate %>点</span>
                            <% else %>
                            <span class="index-stock-quantity">在庫無</span>
                            <span class="index-no-stock-text">【入荷待ち】</span>
                            <% end %>
                         <% end %>
                       </td>
		          </tr>
            </tbody>
        <% end %>
    </table>

  <div class="page-top col-xs-8 col-xs-offset-2">

	<%= paginate @items, class: "paginate" %>
	<p id="pageTop"><a href="#">ページトップへ</a></p>
		<script type='text/javascript'>
			$(function(){
			$('a[href^="#"]').click(function() {
				var speed = 400;
				var href= $(this).attr("href");
					var target = $(href == "#" || href == "" ? 'html' : href);
					var position = target.offset().top;
					$('body,html').animate({scrollTop:position}, speed, 'swing');
					return false;
				});
			});
		</script>
</div>

app/views/items/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<div class="item-detail-title">
					<h3 class="item-detail">商品の詳細</h3>
			</div>
			<div class="border-item-show"></div>



<% if user_signed_in? %>

			<div class="item-detail-content">
				<div class="row">

						<div class="col-xs-10 col-xs-offset-1">

							<div class="before-songlist">

							<div class="col-xs-3">
							<div class="user-samuneiru-position">
								<%= attachment_image_tag @item, :image, :fill, 250, 250, format: 'jpg', fallback: "no_image.jpg" %>
							</div>
							</div>

							<div class="col-xs-9">
							<div class="user-item-detail">
							<div class="user-item-names">
								<span class="user-item-name"><%= @item.name %>
							<% if @favorite.favorited_by?(current_user,@item) %>
						    <%= link_to item_favorite_path(@item.id), method: :delete do %>
						      <i class="fa fa-heart favorite-item-show" aria-hidden="true" style="color: red;"></i>
						 <% end %>
						 <% else %>
							<%= link_to item_favorites_path(@item.id), method: :post do %>
							  <i class="fa fa-heart-o favorite-item-show" aria-hidden="true"></i>
						 <% end %>
						 <% end %>
						 </span>
							</div>
							<div class="user-item-artists">
								<span class="user-item-artist"><%= @item.artist.name %></span>
							</div>
							<div class="user-item-releases">
								<span class="user-item-release">発売日　<%= @item.release.strftime("%Y年%m月%d日") %></span>
							</div>
							<div class="user-item-labels">
								<span class="user-item-label"><%= @item.label.name %></span><br>
							</div>


							<div class="user-item-total-stock-box">
								<div class="user-category-name-box">
									<span class="user-category-name"><%= @item.category.name %></span>
								</div>
								<div class="user-stock-quantity-box">
									<% if @total_arrival-@total_order >= 1 %>
									<span class="user-stock-quantity">在庫残り<%= @item.total_arrival_calculate - @item.total_item_order_calculate %>点</span>
									<% else %>
									<span class="stock-quantity">在庫無</span>
									<% end %>
								</div>

								<div class="user-item-price">
									<span class="user-item-price-text"><%= @item.include_tax_price %> 円<span class="user-item-price-tax">（税込）</span></span>
								</div>

								<div class="user-item-quantity">
									<% if @total_arrival-@total_order >= 1 %>
									<%= form_for (@cart_item), url: cart_items_path do |f| %>

									<%= f.hidden_field :user_id, :value => @user.id %>
									<%= f.hidden_field :item_id, :value => @item.id %>

									<div class="field">
										<div class="user-item-quantity-position">
										<span class="user-item-quantity-text">数量</span>
									<%= f.number_field :quantity, min:"1", max:@total_arrival-@total_order, class:"user-number-field" %>
									<%= f.submit "カートに入れる", class:"btn btn-primary user-cart-in" %>
										</div>
									</div>
									<% end %>
									<% else %>
									<span class="no-stock-text">【入荷待ち】</span>
									<% end %>
								</div>
							</div>
							</div>
							</div>
							</div>
						</div>
					</div>
				</div>



<% else %>

						<div class="col-xs-10 col-xs-offset-1">
							<div class="before-songlist">

							<div class="col-xs-3">
							<div class="user-samuneiru-position">
								<%= attachment_image_tag @item, :image, :fill, 250, 250, format: 'jpg', fallback: "no_image.jpg" %>
							</div>
							</div>

							<div class="col-xs-9">
							<div class="user-item-detail">
							<div class="user-item-names">
								<span class="user-item-name"><%= @item.name %></span>
							</div>
							<div class="user-item-artists">
								<span class="user-item-artist"><%= @item.artist.name %></span>
							</div>
							<div class="user-item-releases">
								<span class="user-item-release">発売日　<%= @item.release.strftime("%Y年%m月%d日") %></span>
							</div>
							<div class="user-item-labels">
								<span class="user-item-label"><%= @item.label.name %></span><br>
							</div>


							<div class="user-item-total-stock-box-before">
								<div class="user-category-name-box">
									<span class="user-category-name"><%= @item.category.name %></span>
								</div>
								<div class="user-stock-quantity-box">
									<% if @total_arrival-@total_order >= 1 %>
									<span class="user-stock-quantity">残り<%= @item.total_arrival_calculate - @item.total_item_order_calculate %>点</span>
									<% else %>
									<span class="stock-quantity">在庫無</span>
									<% end %>
								</div>

								<div class="user-item-price">
									<span class="user-item-price-text-before"><%= @item.include_tax_price %> 円<span class="user-item-price-tax">（税込）</span></span>
								</div>

								</div>
							</div>
							</div>
							</div>
							</div>
						</div>
<% end %>


				<div class="item-detail-content">
					<div class="row">
						<div class="col-xs-8 col-xs-offset-2">

							<h4 class="songlist-index">収録曲一覧</h4>
							<% @disks.each do |disk| %>
							<table class="table table-hover">
								<caption>Disk<%= disk.disk_num %></caption>
								<% disk.songs.each do |song| %>
								<tbody>
									<tr>
										<td width="50px"><%= song.setlist %></td>
										<td><%= song.name %></td>
									</tr>
								</tbody>
								<% end %>
							</table>
							 <% end %>

						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-xs-8 col-xs-offset-2">

				<div class="border-item-show-review"></div>

				<div class="item-show-review-title">
					<span class="item-show-review-title-text"><%= @review.count %>件のカスタマーレビュー</span>
				</div>


					<%= paginate @reviews, class: "paginate" %>
					<% @reviews.each do |review| %>

					<table class="table table-striped table-bordered">
						<caption>投稿日: <%= review.created_at.strftime("%Y年%m月%d日") %><span class="item-show-review-user">ユーザ名: <%= review.user.last_name %>  <%= review.user.first_name %></span></caption>
					<tbody>
						<tr>
							<th width="150">評価</th>
							<td><span id="star<%= review.id %>"></span></td>
						<script>
				          $('#star<%= review.id %>').raty({
				            size: 36,
				            starOff:  '<%= asset_path('star-off.png') %>',
				            starOn : '<%= asset_path('star-on.png') %>',
				            starHalf: '<%= asset_path('star-half.png') %>',
				            half: true,
				            readOnly: true,
				            score: <%= review.rate %>,
				          });
				          </script>
						</tr>
						<tr>
							<th>タイトル</th>
							<td><%= review.title %></td>
						</tr>
						<tr>
							<th>レビュー内容</td>
							<td><%= review.body %></td>
						</tr>
						</tbody>
					</table>
					<% end %>
					<%= paginate @reviews, class: "paginate" %>

					</div>
				</div>

			<div class="back-to-item-index">
			 <%= link_to "< 商品一覧へ", root_path %>
			</div>
		</div>
	</div>