config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # 管理者
  namespace :admin do
    resources :contacts, only: [:create, :index, :show]
    resources :reviews, only: [:edit, :update, :destroy]
    resources :labels, only: [:create, :edit, :update, :new, :destroy]
    resources :categories, only: [:create, :edit, :update, :new, :destroy]
    resources :artists, only: [:create, :edit, :update, :new, :destroy]
    resources :orders, only: [:show, :index, :update]
    resources :arrivals, only: [:new, :create, :index, :edit]
    resources :items, only: [:show, :edit, :new, :create, :update, :index, :destroy]
    get 'items/autocomplete_artist/:term' => 'items#autocomplete_artist'
    get 'items/autocomplete_category/:term' => 'items#autocomplete_category'
    get 'items/autocomplete_label/:term' => 'items#autocomplete_label'
    resources :users, only: [:show, :edit, :update, :index, :destroy]
  end
  # ユーザー
  devise_for :users
  get 'users/:id/exit' => 'users#exit', as: 'exit'
  get 'users/:id/mypage' => 'users#mypage', as: 'mypage'
  resources :items, only: [:index, :show]

  root to: 'items#index'
  resources :cart_items, only: [:create, :destroy, :index, :update]
  resources :orders, only: [:create, :index, :new]
  get 'orders/complete' => 'orders#complete', as:'order_complete'
  get 'reviews/new/:id' => 'reviews#new', as:'new_review'
  post 'orders/pay' => 'orders#pay', as:'order_pay'
  resources :addresses, only: [:create, :update, :destroy]
  resources :credits, only: [:create]
  get 'reviews/:id/new' => 'reviews#new', as: 'reviews_new'
  post 'reviews/:id' => 'reviews#create', as: 'reviews_create'
  resources :contacts, only: [:create, :new]
  resources :users, only: [:edit, :update, :show]
  resources :favorites, only: [:index]
  delete 'favorites/destroy_all' => 'favorites#destroy_all', as: 'destroy_all'
  resources :items, only: [:index, :show] do
  resources :favorites, only: [:create, :destroy]
end
  get 'items/index/result' => 'items#index_result', as: 'index_result'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :last_name, presence: true, length: { maximum: 15 }
  validates :first_name, presence: true, length: { maximum: 15 }
  validates :last_furigana, presence: true, length: { maximum: 20 }
  validates :first_furigana, presence: true, length: { maximum: 20 }
  validates :postal_code, presence: true, length: { maximum: 7 }
  validates :residence, presence: true, length: { maximum: 70 }
  validates :phone_number, presence: true, length: { maximum: 15 }
  validates :email, presence: true
  #validates :password, presence: true, length: { minimum: 6 }
  #validates :password_confirmation, presence: true, length: { minimum: 6 }


  has_many :contacts
  has_many :orders
  has_many :addresses, inverse_of: :user
  accepts_nested_attributes_for :addresses, reject_if: :all_blank, allow_destroy: true
  has_many :favorites, dependent: :destroy
  has_many :favorited_items, through: :favorites, source: :item
  accepts_nested_attributes_for :orders, reject_if: :all_blank, allow_destroy: true
  has_many :favorites
  has_many :cart_items
  has_many :reviews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
acts_as_paranoid
#acts_as_paranoidとは? データを論理削除するためのプラグイン

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    if admin_signed_in?
  	@search = User.ransack(params[:q])
    @user_result = @search.result.page(params[:page]).per(30)
  else
    redirect_to root_path
  end
  end

  def show
    if admin_signed_in?
  	@user = User.find(params[:id])
  else
    redirect_to root_path
  end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render 'indsex'
    end
  end

  def edit
    if admin_signed_in?
  	@user = User.find(params[:id])
  else
    redirect_to root_path
  end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private
  #cocoon用記述。_destroyがないと削除できない。
  def user_params
    params.require(:user).permit(:email,:name, :postal_code, :phone_number, :encrypted_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	#"user/:id"のidには文字列も入るので、注意
  	@user = User.find(params[:id])
    @addresses = Address.where(user_id: current_user.id)
  end

  def exit
  	@user = User.find(params[:id])
  end

  def edit
    @user = current_user
    @address = @user.addresses
    @addresses = @user.addresses
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      flash[:notice] = "アカウント情報の更新に成功しました。"
      redirect_to mypage_path(user.id)
    else
      render "edit"
    end
  end

  def destroy
  end

  def mypage
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_furigana,
      :first_furigana, :postal_code, :residence, :phone_number, :email,
      addresses_attributes: [:id, :name, :address, :postal_code, :_destroy ])
  end
  def password_params
    params.require(:user).permit(:password,:password_confirmation)
  end

  def currect_user
    @user = User.find(params[:id])
    if @user != current_user
        redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<%= render 'admin/sidemenu' %>

<div class="container">
	<div class="row">
		<div class="col-xs-9">
			<h2 class="admin-user-edit-title"><%= @user.last_name %>様</h2>
			<div class="border"></div>
			<div class="col-xs-8 col-xs-offset-1">
				<table class="col-xs-6 table table-striped table-bordered user_show_table" >
					<%= form_for (@user) do |f| %>
					<tbody>
						<tr>
							<div class="field">
								<td ><label class="item-name">名前（漢字）</label></td>
								<td ><%= f.text_field :last_name %>  <%= f.text_field :first_name %></td>
							</div>
						</tr>
						<tr>
							<div class="field">
								<td><label class="item-price">名前（カナ）</label></td>
								<td><%= f.text_field :last_furigana %>  <%= f.text_field :first_furigana %></td>
							</div>
						</tr>
						<tr>
							<div class="field">
								<td><label class="item-name">郵便番号<br><small>(ハイフンを除く７桁)</small></label></td>
								<td><%= f.text_field :postal_code %></td>
							</div>
						</tr>
						<tr>
							<td>住所</td>
							<td><%= f.text_field :residence,class:"col-xs-10" %></td>
						</tr>
						<tr>
							<td>電話番号</td>
							<td><%= f.text_field :phone_number,class:"col-xs-10" %></td>
						</tr>
						<tr>
							<td>メールアドレス</td>
							<td><%= f.text_field :email,class:"col-xs-10" %></td>
						</tr>
					</tbody>
				</table>
				<%= f.submit '保存する', class:'btn btn-primary col-xs-4 col-xs-offset-1' %>
				<%= link_to "削除する" ,admin_user_path(params[:id]), method: :delete,"data-confirm" => "本当に消しますか？", class:"btn btn-danger col-xs-4 col-xs-offset-1" %>
				<% end %>
		 	</div>
		</div>
	<div>
</div>

app/views/admin/users/index.html.erb
<%= render 'admin/sidemenu' %>

<div class="container">
	<div class="row">
		<div class="col-xs-9">
			<h2 class="admin-index-title">顧客一覧</h2>
			<div class="border"></div>
			<div class="search-box col-xs-10 col-xs-offset-1">

				<%= search_form_for @search, url: admin_users_path do |f| %>
  				<%= f.search_field :last_name_or_email_cont, class:"admin-search_field", placeholder: '氏名またはメールアドレスを入力' %>

				<span class="actions">
					<%= f.button :type => "submit", class:'btn btn-primary' do %>
					<i class="fas fa-search"></i>
					<% end %>
				</span>
			 	<% end %>

			 	<% if @user_result.any? %>
				<h5 class="search-result"></h5>


				<table class='col-xs-12 table table-hover table-inverse'>
  					<thead>
    					<tr>
      						<th><b>ID</b></th>
      						<th><b>顧客名</b></th>
      						<th><b>住所</b></th>
      						<th><b>メールアドレス</b></th>
    					</tr>
  					</thead>
  					<% @user_result.each do |user| %>
  					<tbody>
    					<tr>
      						<td><%= user.id %></td>
      						<td><%= link_to(admin_user_path(user)) do %>
									<div><%= user.last_name %>  <%= user.first_name %></div>
								<% end %>
							</td>
      						<td><%= user.residence %></td>
      						<td><%= user.email %></td>
    					</tr>
    					<% end %>
  					</tbody>
				</table>
				<% else %>
			 		<h6>検索する商品がありません。キーワードを変えてください。</h6>
			 	<% end %>
			</div>
		</div>
	</div>
   <div class="row">
	<div class="col-xs-6 col-xs-offset-3">
	 <p id="pageTop"><a href="#">ページのトップへ戻る</a></p>
	</div>
   </div>
</div>

app/views/admin/users/show.html.erb
<%= render 'admin/sidemenu' %>

<div class="container">
	<div class="row">
		<div class="col-xs-9">
			<div>
				<h2 class="admin-index-title" ><%= @user.last_name %>様</h2>
				<h5 class="edit_user"><%= link_to "顧客情報の編集", edit_admin_user_path(@user), class: "glyphicon glyphicon-pencil" %></h5>
			</div>
			<div class="border"></div>
			</div>
			<div class="col-xs-6 col-xs-offset-1">
			<table class="col-xs-9 table table-striped table-bordered user_show_table">
				<tbody>
					<tr>
						<div class="field">
							<th class="user_table">ID</th>
							<th class="user_table"><%= @user.id %></th>
						</div>
					</tr>
					<tr>
						<div class="field">
							<th class="user_table">名前（漢字）</th>
							<th class="user_table"><%= @user.last_name %>  <%= @user.first_name %></th>
						</div>
					</tr>
					<tr>
						<div class="field">
							<th class="user_table">名前（カナ）</th>
							<th class="user_table"><%= @user.last_furigana %><%= @user.first_furigana %></th>
						</div>
					</tr>
					<tr>
						<th class="user_table">郵便番号<br><small>(ハイフンを除く７桁)</small></th>
						<th class="user_table"><%= @user.postal_code %></th>
					</tr>
					<tr>
						<th class="user_table">住所</th>
						<th class="user_table"><%= @user.residence %></th>
					</tr>
					<tr>
						<th class="user_table">電話番号</th>
						<th class="user_table"><%= @user.phone_number %></th>
					</tr>
					<tr>
						<th class="user_table">メールアドレス</th>
						<th class="user_table"><%= @user.email %></th>
					</tr>
				</tbody>
			</table>
			</div>
			<%= link_to(admin_order_path(@user.id)) do %>
			<div class="col-xs-2 col-xs-offset-6 admin-usershow-box">受注履歴へ</div>
			<% end %>
	</div>
</div>